// STM32 HAL headers (auto-generated by STM32CubeMX)
#include "main.h"
#include "stm32l4xx_hal.h"
#include "tim.h"       // Timer 2 for PWM buzzer control
#include "usart.h"     // For serial output
#include "gpio.h"      // GPIO control
#include "adc.h"       // ADC for joystick input
#include "rng.h"       // RNG for randomized ball reset

// AUTO-GENERATED STM32 FUNCTION PROTOTYPES - DO NOT EDIT
void SystemClock_Config(void);
void PeriphCommonClock_Config(void);

// HAL Drivers and Utilities
#include "Buzzer.h"    // Buzzer control via PWM
#include "PWM.h"       // PWM control for LED 
#include "LCD.h"       // LCD display driver
#include "Joystick.h"  // Joystick input
#include "Utils.h"     // Common utility types

// Menu System and Input
#include "Menu.h"      // Menu state machine and UI
#include "InputHandler.h" // Input reading
#include "FightMenu.h"
#include "Boss.h"
#include <stdint.h>
#include <stdio.h>
#include <math.h>
#include "Actions.h"
#include "Bulb.h"
#include "Attack.h"
#include "Music.h"
// ===== FORWARD DECLARATIONS FOR GAMES =====
// Each game implements a Run function that returns the next state
FIGHTSTATE ACTMESSAGE(void);
FIGHTSTATE MERCYMESSAGE(void);
FIGHTSTATE ITEMRUN(void);
FIGHTSTATE AttackFunction(void);
//FIGHTSTATE AttackSliderMainFunction(void);
FIGHTSTATE BossAttackFunction(Boss *b,Bulb_t *Bulb,Bulbparams_t *BulbParam);
ITEMSTATES CapacitorFunc(Bulbparams_t *BulbParam);
ITEMSTATES BatteryFunc(Bulbparams_t *BulbParam);
ITEMSTATES ItemSelection(ItemSelected_t *item);
PHASE BossRenderFunction(Boss *b);


PHASE MusicPlayer(Boss*b);
#define MAINTIMER 200
// ===== MENU SYSTEM STATE =====
OptionSelection_t op;
Boss b;

ItemSelected_t item;
Bulbparams_t BulbParam;
Bulb_t Bulb;
Slider_t sli;
DMG_t d;
extern Buzzer_cfg_t buzzer_cfg;
extern PWM_cfg_t pwm_cfg;
/**
 * @brief Game 1 Implementation - Student can modify
 * 
 * EXAMPLE: Shows how to use PWM LED for visual feedback
 * This is a placeholder with a bouncing animation that changes LED brightness.
 * Replace this with your actual game logic!
 */



// Frame rate for this game (in milliseconds)
#define GAME1_FRAME_TIME_MS 30  // ~33 FPS

MenuState Game1_Run(void) {
    // Initialize game state
    
    // ===== INITNIALISE SYSTEM =====

    FightMenuInit(&op);
    BossInit(&b);
    ItemInit(&item);
    BulbParamInit(&BulbParam);
  // INITIALISE FIGHSTATE
    FIGHTSTATE selected_state = ATKMENU;
    
    // Play a brief startup sound
    buzzer_tone(&buzzer_cfg, 1000, 30);  // 1kHz at 30% volume
    HAL_Delay(50);  // Brief beep duration
    buzzer_off(&buzzer_cfg);  // Stop the buzzer
    
    MenuState exit_state = MENU_STATE_HOME;  // Default: return to menu
    
    // Game's own loop - runs until exit condition
    while (1) {
        InputRead();
         if (current_input.btn3_pressed) {
            PWM_SetDuty(&pwm_cfg, 50);  // Reset LED
            exit_state = MENU_STATE_HOME;
            break;  // Exit game loop
        }
         // FSM based on FIGHSTATE , updates between action -----> bossfight -----> menu and then loops depening on whether
   //Player is alive, boss is alive or an action is selected.
    switch (selected_state){
      case ATKMENU : 
      selected_state = FightMenuUpdate(&op);
      break;
      case FIGHT: 
      selected_state = AttackFunction();
      selected_state = BossAttackFunction(&b,&Bulb,&BulbParam);
      break;
      case ITEM:
      selected_state = ITEMRUN();
      selected_state = BossAttackFunction(&b,&Bulb,&BulbParam);
      break;
      case MERCY:
      selected_state = MERCYMESSAGE();
      selected_state = BossAttackFunction(&b,&Bulb,&BulbParam);
      break;
      case ACT :
      selected_state = ACTMESSAGE();
      selected_state = BossAttackFunction(&b,&Bulb,&BulbParam);
      break;
      case BOSSATTACK :
      selected_state = BossAttackFunction(&b,&Bulb,&BulbParam);
      selected_state = FightMenuUpdate(&op);
      break;
    }

      MusicPlayer(&b); // allows music to constantly play
  }
  return 0;
}
